name: Release Creation

on:
  release:
    types: [published]

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write # This permission is needed to upload files to the release

    steps:
      # 1. Checkout your repository's code
      - name: Checkout Repository
        uses: actions/checkout@v4

      # 2. Substitute the Manifest and Download URLs in the module.json
      - name: Substitute Manifest Details
        uses: im-open/variable-substitution@v2
        with:
          files: "module.json"
        env:
          version: ${{ github.event.release.tag_name }}
          url: https://github.com/${{ github.repository }}
          manifest: https://github.com/${{ github.repository }}/releases/latest/download/module.json
          download: https://github.com/${{ github.repository }}/releases/download/${{ github.event.release.tag_name }}/module.zip

      # 3. Create a zip file with all required module files
      - name: Create Zip Archive
        run: zip -r ./module.zip module.json README.md ChangeLog.md styles/ scripts/ templates/ ui/ lang/

      # 4. Upload the zip and manifest to the release
      - name: Update Release with Files
        uses: ncipollo/release-action@v1
        with:
          allowUpdates: true
          token: ${{ secrets.GITHUB_TOKEN }}
          artifacts: "./module.json, ./module.zip"
          tag: ${{ github.event.release.tag_name }}

      # 5. Publish the module to the Foundry VTT website
      - name: Publish to FoundryVTT Website
        uses: cs96and/FoundryVTT-release-package@v1
        with:
          package-token: ${{ secrets.PACKAGE_TOKEN }}
          manifest-url: https://github.com/${{ github.repository }}/releases/download/${{ github.event.release.tag_name }}/module.json
          notes-url: "https://github.com/${{ github.repository }}/blob/main/ChangeLog.md"
